apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-backend
  labels:
    app: node-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      name: backend-Pod
      labels:
        app: node-app
    spec:  
       containers:  
        - name: backend-container 
          image: dhanyashree/nodeserver:c2
          imagePullPolicy: Always
          ports:
          - containerPort: 5000
          env:
          - name: MONGO_ROOT_USERNAME
            value: backend-service 
              
            
        
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      serviceAccountName: dhanya-account 
      ServiceAccount: dhanya-account
      securityContext: {}
      schedulerName: default-scheduler
---
#frontend service
kind: Service
apiVersion: v1
metadata:
  name: node-service-frontend
  namespace: dhanya-assign
spec:
  type: LoadBalancer
  ports:
    - name: targetss
      protocol: TCP
      port: 3000
      targetPort: 3000
  selector:
    app: node-app
---
#frontend route
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: node-route
  namespace: dhanya-assign
  labels:
        app: node-app
spec:
  to:
    kind: Service
    name: node-service-frontend
    weight: 100
  port:
    targetPort: targetss
---
#backend deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-backend
  namespace: dhanya-assign
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      - name: node-backend
        image: dhanyashree/nodeserver:a2
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env: 
        - name: USERNAME
#          value: myuser       value 
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: username
        - name: PASSWORD
#          value: myuser       value 
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: password
        - name: DB_URL
            valueFrom: 
             ConfigMapKeyRef: 
               name: dhanya-config
               key: MONGO_URL
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      serviceAccountName: dhanya-account 
      ServiceAccount: dhanya-account
      securityContext: {}
      schedulerName: default-scheduler
   
---
#backend service
kind: Service
apiVersion: v1
metadata:
  name: node-service-backend
  namespace: dhanya-assign

spec:
  type: ClusterIP
  ports:
    - name: backend
      protocol: TCP
      port: 5000
      targetPort: 5000
  selector:
    app: node-app