apiVersion: v1
kind: Pod 
metadata: 
  name: backend-Pod
  labels:
    app: node-app
spec:
  containers:
   - name: backend-container 
     image: 
     imagePullPolicy: Always
     ports:
      - containerPort: 5000
      env:
       - name: MONGO_ROOT_PASSWORD
         valueFrom:
           secretKeyRef:
             name: mongo-secret
             key: password
       - name: MONGO_ROOT_USERNAME
         valueFrom: 
           secretKeyRef: 
             name: mongo-secret
             key: username
        - name: app-configmap
          valueFrom:
            ConfigMapKeyRef:
              name: dhanya-configmap
              key: MONGO_URI


---
#BAckend

apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-backend
  labels:
    app: node-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      name: backend-Pod
      labels:
        app: node-app
    spec:  
       containers:  
        - name: backend-container 
          image: dhanyashree/nodeserver:c2
          imagePullPolicy: Always
          ports:
          - containerPort: 5000
          env:
          - name: MONGO_ROOT_USERNAME
            valueFrom: 
              secretKeyRef:
                name: mongo-secret
                key: username
          - name: MONGO_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mongo-secret
                key: password
         
          - name: DB_URL
            value: 'mongo-service.dhanya-assign.svc.cluster.local:27017/data'
          - name: NODE_ENV
            value: production
          - name: PORT
              value: '5000'

    
    
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-frontend
  labels:
    app: node-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      name: frontend-Pod
      labels:
        app: node-app
    spec:  
       containers:  
        - name: frontend-container 
          image: dhanyashree/nodeclient:c2
          imagePullPolicy: Always
          ports:
          - containerPort: 3000
        env:
          - name: REACT_APP_API_BASE_URL
            value: backend-service 
             
          


